import { CloudSun, Droplets, Thermometer } from "lucide-react";
import { MONTHS, type ClimateProfile } from "@/lib/travel/types";

export default function ClimateTable({ climate, name }: { climate: ClimateProfile; name: string }) {
  return <section id="climate" className="scroll-mt-8"><div className="mb-6 flex items-center gap-3"><CloudSun className="text-coral" size={26} /><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-grape/55">Choose your season</p><h2 className="font-heading text-3xl font-semibold">A year in {name}</h2></div></div>
    <p className="mb-6 max-w-3xl leading-relaxed text-grape/75">A month-by-month guide to typical conditions, so you can match your trip to the weather you enjoy. These are regional averages for {climate.baseline}, rather than a forecast for your dates.</p>
    <div className="overflow-x-auto rounded-3xl border border-grape/10 bg-white"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Monthly climate averages for {name}, {climate.baseline}</caption><thead className="bg-periwinkle/15"><tr><th scope="col" className="px-5 py-4 font-semibold">Month</th><th scope="col" className="px-5 py-4 font-semibold"><span className="inline-flex items-center gap-2"><Thermometer size={15} />Mean temperature</span></th><th scope="col" className="px-5 py-4 font-semibold"><span className="inline-flex items-center gap-2"><Droplets size={15} />Precipitation</span></th><th scope="col" className="px-5 py-4 font-semibold">Cloud cover</th></tr></thead><tbody>{climate.months.map(m => <tr key={m.month} className="border-t border-grape/5 odd:bg-ivory/25"><th scope="row" className="px-5 py-3 font-semibold">{MONTHS[m.month - 1]}</th><td className="px-5 py-3">{m.temperatureC.toFixed(1)}°C</td><td className="px-5 py-3">{m.precipitationMm} mm/month</td><td className="px-5 py-3">{m.cloudCoverPercent}%</td></tr>)}</tbody></table></div>
    <details className="mt-4 rounded-2xl bg-white/60 p-4 text-sm text-grape/65"><summary className="cursor-pointer font-semibold text-grape">Source, calculation and coverage</summary><p className="mt-3 leading-relaxed">{climate.methodology} For islands and regions, local conditions can differ substantially between coast and higher ground.</p><p className="mt-2">Representative point: {climate.location.latitude.toFixed(2)}°, {climate.location.longitude.toFixed(2)}°. Source: <a href={climate.source.url} className="underline underline-offset-4">{climate.source.name}</a>. Snowfall and sunshine-hour statistics are unavailable in this dataset.</p></details>
  </section>;
}
