import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Compass, Heart, MapPin, Users, Footprints, ChevronRight } from "lucide-react";
import type { PublishedPage, PageSummary } from "@/lib/travel/types";
import { SITE_URL } from "@/lib/travel/repository";
import TravelNavigation from "./TravelNavigation";
import ClimateTable from "./ClimateTable";
import HolidayChat from "./HolidayChat";
import TravelCard from "./TravelCard";
import Footer from "@/components/common/Footer";

export default function GuidePage({ page, related, variants }: { page: PublishedPage; related: PageSummary[]; variants: PageSummary[] }) {
  const { content: p } = page;
  const d = p.destination;
  const themed = p.type === "family" || p.type === "couples";
  const advice = p.type === "family" ? d.family : d.couples;
  const Icon = p.type === "family" ? Users : p.type === "couples" ? Heart : Compass;
  const countryName = d.country.charAt(0).toUpperCase() + d.country.slice(1);
  const base = d.kind === "country" ? `/holidays/${d.id}` : `/holidays/${d.country}/${d.id}`;
  const breadcrumbs = [{ name: "Holidays", path: "/holidays" }, { name: countryName, path: `/holidays/${d.country}` }, ...(d.kind === "country" ? [] : [{ name: d.name, path: base }])];
  const jsonLd = [
    { "@context": "https://schema.org", "@type": "WebPage", name: p.title, description: p.description, url: `${SITE_URL}${page.path}`, dateModified: page.updatedAt, inLanguage: "en-GB", image: d.image.url, about: { "@type": "Place", name: d.name, sameAs: p.geography.source.url } },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: breadcrumbs.map((b, i) => ({ "@type": "ListItem", position: i + 1, name: b.name, item: `${SITE_URL}${b.path}` })) },
  ];
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><div className="relative overflow-hidden"><TravelNavigation />
    <header className="relative mx-auto grid max-w-7xl gap-8 px-5 pb-12 pt-32 md:px-8 md:pt-40 lg:grid-cols-[1.05fr_0.95fr] lg:gap-12 lg:pb-20">
      <div className="flex flex-col justify-center"><nav aria-label="Breadcrumb" className="mb-8 flex flex-wrap items-center gap-2 text-xs font-semibold text-grape/55">{breadcrumbs.map((b, i) => <span key={b.path} className="inline-flex items-center gap-2">{i ? <ChevronRight size={12} /> : null}<Link href={b.path} className="hover:text-coral">{b.name}</Link></span>)}{themed || p.type === "itinerary" ? <span className="inline-flex items-center gap-2"><ChevronRight size={12} />{p.type === "itinerary" ? `${p.days} days` : p.type === "family" ? "Family" : "Couples"}</span> : null}</nav>
        <span className="mb-5 inline-flex items-center gap-2 self-start rounded-full border border-periwinkle/30 bg-periwinkle/15 px-4 py-2 text-xs font-bold uppercase tracking-[0.13em]"><Icon size={15} />{p.type === "itinerary" ? "Your days, thoughtfully arranged" : themed ? "A holiday with your people" : "A little wanderlust, well planned"}</span>
        <h1 className="max-w-2xl font-heading text-5xl font-semibold leading-[1.07] tracking-tight md:text-6xl">{p.title.replace(": a relaxed itinerary", "").replace(", thoughtfully planned", "")}<span className="mt-2 block text-coral">{p.type === "itinerary" ? "At your own pace." : "Made for you."}</span></h1>
        <p className="mt-6 max-w-xl text-base leading-relaxed text-grape/75 md:text-lg">{themed ? advice.intro : d.summary}</p>
        <div className="mt-8 flex flex-wrap items-center gap-4"><a href="#request-itinerary" className="inline-flex items-center gap-2 rounded-full bg-coral px-6 py-3.5 font-bold text-white shadow-sm transition hover:bg-salmon">Plan my {d.name} trip<ArrowUpRight size={18} /></a><a href={p.type === "country" || d.kind === "country" ? "#explore" : "#climate"} className="inline-flex items-center gap-2 text-sm font-semibold">{d.kind === "country" ? "Find your destination" : "Find your season"}<ArrowRight size={16} /></a></div>
      </div>
      <figure className="relative min-h-80 overflow-hidden rounded-[2.5rem] bg-periwinkle/20 shadow-sm md:min-h-[490px]"><Image src={d.image.url} alt={d.image.alt} fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-grape/60 via-transparent to-transparent" /><figcaption className="absolute bottom-5 left-5 right-5 flex items-center justify-between gap-4 text-xs text-white"><span className="flex items-center gap-1.5 font-semibold"><MapPin size={14} />{d.name}{d.kind !== "country" ? `, ${countryName}` : ""}</span><a href={d.image.creditUrl} className="max-w-[55%] text-right text-white/85 underline decoration-white/40 underline-offset-4">{d.image.credit} · {d.image.licence}</a></figcaption></figure>
    </header>
    <main className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-4 rounded-3xl border border-white bg-white/65 p-6 md:grid-cols-3 md:p-8"><div className="flex gap-3"><Compass className="mt-1 shrink-0 text-coral" size={20} /><div><p className="text-xs font-bold uppercase tracking-wider text-grape/50">A lovely fit for</p><p className="mt-2 text-sm font-semibold leading-relaxed">{d.bestFor}</p></div></div><div className="flex gap-3"><Footprints className="mt-1 shrink-0 text-coral" size={20} /><div><p className="text-xs font-bold uppercase tracking-wider text-grape/50">The right pace</p><p className="mt-2 text-sm font-semibold leading-relaxed">{d.pace}</p></div></div><div className="flex gap-3"><Users className="mt-1 shrink-0 text-coral" size={20} /><div><p className="text-xs font-bold uppercase tracking-wider text-grape/50">Start from the UK</p><p className="mt-2 text-sm font-semibold leading-relaxed">Your departure city, dates and GBP budget shape the request.</p></div></div></div>
      <div className="grid gap-12 py-14 lg:grid-cols-[1fr_260px] lg:gap-14">
        <div className="min-w-0 space-y-14">
          {themed ? <section id="explore"><p className="text-xs font-bold uppercase tracking-widest text-grape/50">Thoughtful details</p><h2 className="mt-2 font-heading text-3xl font-semibold">{p.type === "family" ? "More happy moments. Fewer rushed days." : "Make room for the two of you."}</h2><div className="mt-6 space-y-3">{advice.tips.map((tip, i) => <div key={tip} className="flex gap-4 rounded-2xl bg-white p-5"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-periwinkle/20 font-heading font-semibold text-grape">{i + 1}</span><p className="text-sm leading-relaxed text-grape/80">{tip}</p></div>)}</div></section> : null}
          {d.kind === "country" ? <section id={themed ? "destinations" : "explore"}><p className="text-xs font-bold uppercase tracking-widest text-grape/50">Different places. Different possibilities.</p><h2 className="mt-2 font-heading text-3xl font-semibold">Find your corner of {d.name}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{p.children.map(child => <Link key={child.id} href={`/holidays/${child.country}/${child.id}`} className="group rounded-3xl border border-grape/5 bg-white p-6"><h3 className="flex items-center justify-between gap-4 font-heading text-2xl font-semibold">{child.name}<ArrowUpRight size={18} className="text-coral" /></h3><p className="mt-3 text-sm font-semibold">{child.bestFor}</p><p className="mt-3 text-sm leading-relaxed text-grape/70">{child.summary}</p></Link>)}</div></section> : <section id={themed ? "experiences" : "explore"}><p className="text-xs font-bold uppercase tracking-widest text-grape/50">A few things worth slowing down for</p><h2 className="mt-2 font-heading text-3xl font-semibold">A little of what makes {d.name}, {d.name}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{d.experiences.map((e, i) => <article key={e.name} className="rounded-3xl border border-grape/5 bg-white p-6"><p className="font-heading text-3xl text-periwinkle">0{i + 1}</p><h3 className="mt-3 font-heading text-xl font-semibold">{e.name}</h3><p className="mt-3 text-sm leading-relaxed text-grape/75">{e.description}</p></article>)}</div></section>}
          <section id="where-to-stay"><h2 className="font-heading text-3xl font-semibold">{d.kind === "country" ? "Choose the kind of holiday you want" : "A base that feels right"}</h2><p className="mt-4 leading-relaxed text-grape/75">{d.gettingAround}</p><div className="mt-6 overflow-x-auto rounded-3xl border border-grape/10 bg-white"><table className="w-full min-w-[500px] text-left text-sm"><caption className="sr-only">{d.kind === "country" ? "Destination" : "Neighbourhood"} comparison for {d.name}</caption><thead className="bg-periwinkle/15"><tr><th scope="col" className="p-4">{d.kind === "country" ? "Destination" : "Area"}</th><th scope="col" className="p-4">The feel</th><th scope="col" className="p-4">Keep in mind</th></tr></thead><tbody>{d.areas.map(a => <tr key={a.name} className="border-t border-grape/5"><th scope="row" className="p-4 font-semibold">{a.name}</th><td className="p-4 text-grape/75">{a.character}</td><td className="p-4 text-grape/75">{a.consider}</td></tr>)}</tbody></table></div></section>
          {p.climate ? <ClimateTable climate={p.climate} name={d.name} /> : <section id="climate"><h2 className="font-heading text-3xl font-semibold">Choose a season, then a region</h2><p className="mt-4 leading-relaxed text-grape/75">{d.timing}</p><p className="mt-3 text-sm text-grape/65">Each destination guide has its own monthly climate table. A single country-wide average would hide the differences that matter to your trip.</p></section>}
          {d.kind !== "country" ? <section id="itinerary"><p className="text-xs font-bold uppercase tracking-widest text-grape/50">An idea to make your own</p><h2 className="mt-2 font-heading text-3xl font-semibold">{p.days || d.days.length} days, with space to breathe</h2><p className="mt-4 leading-relaxed text-grape/75">{p.type === "itinerary" ? "This suggested route gives each day a focus and keeps evenings flexible. Choose the activities that suit you; reservations and transport are arranged around your dates." : themed ? `Use this starting route alongside the ${p.type === "family" ? "family pacing and access considerations" : "couples suggestions"} above. Your final plan can have fewer sights, extra rest days or different experiences.` : "A suggested starting route, rather than a fixed package. Our agents can change the pace, experiences and length around your trip."}</p><ol className="mt-7 space-y-4">{d.days.slice(0, p.days || d.days.length).map((day, i) => <li key={day.title} className="rounded-3xl border border-grape/5 bg-white p-6"><div className="flex items-center gap-4"><span className="rounded-full bg-coral/10 px-3 py-2 text-xs font-bold text-grape">Day {i + 1}</span><h3 className="font-heading text-xl font-semibold">{day.title}</h3></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3">{[["Morning", day.morning], ["Afternoon", day.afternoon], ["Evening", day.evening]].map(([label, text]) => <div key={label}><dt className="font-semibold text-grape/55">{label}</dt><dd className="mt-2 leading-relaxed text-grape/80">{text}</dd></div>)}</dl></li>)}</ol><p className="mt-4 text-sm leading-relaxed text-grape/65">{d.timing}</p></section> : null}
          <section id="sources" className="rounded-3xl border border-grape/10 bg-white/55 p-6"><h2 className="font-heading text-xl font-semibold">The detail behind the daydream</h2><p className="mt-3 text-sm leading-relaxed text-grape/70">Planning suggestions are original editorial ideas, informed by the public sources below. They are not confirmed bookings. Check current opening hours, access arrangements and entry requirements with the relevant official sources before travelling.</p><ul className="mt-4 space-y-2 text-sm">{[...d.sources, p.geography.source, ...(p.climate ? [p.climate.source] : [])].map(s => <li key={s.url}><a href={s.url} className="inline-flex items-center gap-1.5 font-semibold underline decoration-periwinkle underline-offset-4">{s.name}<ArrowUpRight size={13} /></a></li>)}</ul><p className="mt-4 text-xs text-grape/55">Content updated {new Date(page.updatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" })}. Geography: Wikidata, CC0. Photography: {d.image.credit}, {d.image.licence}; see the linked image source.</p></section>
        </div>
        <aside className="hidden lg:block"><div className="sticky top-8 rounded-3xl border border-grape/10 bg-white/75 p-6"><p className="text-xs font-bold uppercase tracking-widest text-grape/50">Your guide</p><nav aria-label="On this page" className="mt-5 space-y-4 text-sm font-semibold">{[["#explore", d.kind === "country" ? "Find your destination" : themed ? "Your kind of holiday" : "Worth exploring"], ["#where-to-stay", "Choose your base"], ["#climate", "Find your season"], ...(d.kind !== "country" ? [["#itinerary", "A suggested itinerary"]] : []), ["#sources", "Sources & detail"]].map(([href, label]) => <a key={href} href={href} className="block transition hover:text-coral">{label}</a>)}</nav><a href="#request-itinerary" className="mt-7 flex items-center justify-between rounded-2xl bg-periwinkle/15 p-4 text-sm font-bold">Make it yours<ArrowUpRight size={17} /></a></div></aside>
      </div>
      {variants.length ? <nav aria-label={`More ways to plan ${d.name}`} className="mb-10 rounded-3xl bg-white p-6"><h2 className="font-heading text-2xl font-semibold">Your people. Your pace.</h2><div className="mt-4 flex flex-wrap gap-3">{variants.map(v => <Link key={v.path} href={v.path} className="inline-flex items-center gap-2 rounded-full border border-grape/10 px-5 py-3 text-sm font-semibold hover:bg-periwinkle/15">{v.type === "family" ? `Family holidays in ${d.name}` : v.type === "couples" ? `Couples holidays in ${d.name}` : v.type === "itinerary" ? v.title.replace(": a relaxed itinerary", "") : `${d.name} destination guide`}<ArrowUpRight size={16} /></Link>)}</div></nav> : null}
      <HolidayChat sourcePath={page.path} destination={d.name} pageType={p.type} duration={p.days} />
      {related.length ? <section className="py-14"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-grape/50">Keep the inspiration going</p><h2 className="mt-2 font-heading text-3xl font-semibold">Another way to see {countryName}</h2></div><Link href="/holidays" className="inline-flex items-center gap-2 text-sm font-semibold">All destinations<ArrowRight size={16} /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{related.map(r => <TravelCard key={r.path} page={r} />)}</div></section> : null}
    </main></div><Footer /></>;
}
